# SPDX-FileCopyrightText: 2025-2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'
linters:
  default: none
  enable:
    # all
    - asciicheck
    - bidichk
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic  # todo: setup
    - gocyclo
    - godoclint  # todo: setup
    - godot
    - gomoddirectives  # todo: setup
    - goprintffuncname
    - gosec
    - govet  # todo: setup
    - iface
    - inamedparam
    - iotamixing
    - ireturn
    - maintidx
    - makezero
    - mirror
    - modernize
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - recvcheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # net/http
    - bodyclose
    - canonicalheader
    - nosprintfhostport
    # context
    - containedctx
    - contextcheck
    # encoding/json
    - errchkjson
    # i18n/l10n
    - gosmopolitan
  settings:
    embeddedstructfieldcheck:
      forbid-mutex: true
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    nolintlint:
      require-specific: true
    perfsprint:
      strconcat: false
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
