//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ActiveInviteLinkStateStatus.
const (
	ActiveInviteLinkStateStatusActive ActiveInviteLinkStateStatus = "active"
)

// Valid indicates whether the value is a known member of the ActiveInviteLinkStateStatus enum.
func (e ActiveInviteLinkStateStatus) Valid() bool {
	switch e {
	case ActiveInviteLinkStateStatusActive:
		return true
	default:
		return false
	}
}

// Defines values for ExpiredInviteLinkStateStatus.
const (
	Expired ExpiredInviteLinkStateStatus = "expired"
)

// Valid indicates whether the value is a known member of the ExpiredInviteLinkStateStatus enum.
func (e ExpiredInviteLinkStateStatus) Valid() bool {
	switch e {
	case Expired:
		return true
	default:
		return false
	}
}

// Defines values for IntroducedUserStateStatus.
const (
	Introduced IntroducedUserStateStatus = "introduced"
)

// Valid indicates whether the value is a known member of the IntroducedUserStateStatus enum.
func (e IntroducedUserStateStatus) Valid() bool {
	switch e {
	case Introduced:
		return true
	default:
		return false
	}
}

// Defines values for RevokedInviteLinkStateStatus.
const (
	Revoked RevokedInviteLinkStateStatus = "revoked"
)

// Valid indicates whether the value is a known member of the RevokedInviteLinkStateStatus enum.
func (e RevokedInviteLinkStateStatus) Valid() bool {
	switch e {
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for UnintroducedUserStateStatus.
const (
	Unintroduced UnintroducedUserStateStatus = "unintroduced"
)

// Valid indicates whether the value is a known member of the UnintroducedUserStateStatus enum.
func (e UnintroducedUserStateStatus) Valid() bool {
	switch e {
	case Unintroduced:
		return true
	default:
		return false
	}
}

// Defines values for ListInviteLinksParamsStatus.
const (
	ListInviteLinksParamsStatusActive  ListInviteLinksParamsStatus = "active"
	ListInviteLinksParamsStatusExpired ListInviteLinksParamsStatus = "expired"
	ListInviteLinksParamsStatusRevoked ListInviteLinksParamsStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ListInviteLinksParamsStatus enum.
func (e ListInviteLinksParamsStatus) Valid() bool {
	switch e {
	case ListInviteLinksParamsStatusActive:
		return true
	case ListInviteLinksParamsStatusExpired:
		return true
	case ListInviteLinksParamsStatusRevoked:
		return true
	default:
		return false
	}
}

// ActiveInviteLinkState defines model for ActiveInviteLinkState.
type ActiveInviteLinkState struct {
	ExpiresAt *string                     `json:"expires_at"`
	Status    ActiveInviteLinkStateStatus `json:"status"`
}

// ActiveInviteLinkStateStatus defines model for ActiveInviteLinkState.Status.
type ActiveInviteLinkStateStatus string

// Code defines model for Code.
type Code = string

// CodeDelivery Says that a code was sent. It carries neither the code nor the address on purpose: the code belongs in the mailbox, and the address is what the caller has just supplied.
type CodeDelivery struct {
	ExpiresAt string `json:"expires_at"`

	// RetryAfter Seconds before another code may be requested for this address.
	RetryAfter int `json:"retry_after"`
}

// CreateCodeRequest defines model for CreateCodeRequest.
type CreateCodeRequest struct {
	Email Email `json:"email"`
}

// CreateIntroductionRequest defines model for CreateIntroductionRequest.
type CreateIntroductionRequest struct {
	// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
	Username Username `json:"username"`
}

// CreateInviteLinkRequest Omitting expires_at creates a link that never expires.
type CreateInviteLinkRequest struct {
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Code  Code  `json:"code"`
	Email Email `json:"email"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name TeamName `json:"name"`
}

// Email defines model for Email.
type Email = openapi_types.Email

// ExpiredInviteLinkState defines model for ExpiredInviteLinkState.
type ExpiredInviteLinkState struct {
	ExpiredAt string                       `json:"expired_at"`
	Status    ExpiredInviteLinkStateStatus `json:"status"`
}

// ExpiredInviteLinkStateStatus defines model for ExpiredInviteLinkState.Status.
type ExpiredInviteLinkStateStatus string

// IntroducedUserState defines model for IntroducedUserState.
type IntroducedUserState struct {
	Status IntroducedUserStateStatus `json:"status"`

	// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
	Username Username `json:"username"`
}

// IntroducedUserStateStatus defines model for IntroducedUserState.Status.
type IntroducedUserStateStatus string

// InvalidCodeProblem defines model for InvalidCodeProblem.
type InvalidCodeProblem struct {
	AttemptsLeft int     `json:"attempts_left"`
	Detail       *string `json:"detail,omitempty"`
	Instance     *string `json:"instance,omitempty"`
	Status       int     `json:"status"`
	Title        string  `json:"title"`
	Type         *string `json:"type,omitempty"`
}

// InviteLink defines model for InviteLink.
type InviteLink struct {
	Code      string          `json:"code"`
	CreatedAt string          `json:"created_at"`
	State     InviteLinkState `json:"state"`
	UseCount  int             `json:"use_count"`
}

// InviteLinkState defines model for InviteLinkState.
type InviteLinkState struct {
	union json.RawMessage
}

// Pass The keys to a session, not the session itself. The access token is short-lived and travels in Authorization on every request. The refresh token is long-lived and buys a fresh pair once the access token dies; it is the one worth stealing, and belongs where scripts cannot reach it.
type Pass struct {
	AccessExpiresAt string `json:"access_expires_at"`
	AccessToken     string `json:"access_token"`

	// RefreshExpiresAt Moves forward with every refresh: a session dies from disuse, not from age.
	RefreshExpiresAt string `json:"refresh_expires_at"`
	RefreshToken     string `json:"refresh_token"`
}

// Problem RFC 9457 Problem Details for HTTP APIs.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// RefreshSessionRequest defines model for RefreshSessionRequest.
type RefreshSessionRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RevokedInviteLinkState defines model for RevokedInviteLinkState.
type RevokedInviteLinkState struct {
	RevokedAt string                       `json:"revoked_at"`
	Status    RevokedInviteLinkStateStatus `json:"status"`
}

// RevokedInviteLinkStateStatus defines model for RevokedInviteLinkState.Status.
type RevokedInviteLinkStateStatus string

// Team defines model for Team.
type Team struct {
	CreatedAt string   `json:"created_at"`
	Id        string   `json:"id"`
	Name      TeamName `json:"name"`
}

// TeamName defines model for TeamName.
type TeamName = string

// UnintroducedUserState The person exists and nothing else about them is known yet. Carries no name — not an empty one, none at all, so that "introduced without a name" cannot be said.
type UnintroducedUserState struct {
	Status UnintroducedUserStateStatus `json:"status"`
}

// UnintroducedUserStateStatus defines model for UnintroducedUserState.Status.
type UnintroducedUserStateStatus string

// User defines model for User.
type User struct {
	CreatedAt string    `json:"created_at"`
	Id        string    `json:"id"`
	State     UserState `json:"state"`
}

// UserState defines model for UserState.
type UserState struct {
	union json.RawMessage
}

// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
type Username = string

// XUserId defines model for XUserId.
type XUserId = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RevokeInviteLinkParams defines parameters for RevokeInviteLink.
type RevokeInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// AcceptInviteLinkParams defines parameters for AcceptInviteLink.
type AcceptInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateTeamParams defines parameters for CreateTeam.
type CreateTeamParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// GetTeamParams defines parameters for GetTeam.
type GetTeamParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListInviteLinksParams defines parameters for ListInviteLinks.
type ListInviteLinksParams struct {
	Status *ListInviteLinksParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListInviteLinksParamsStatus defines parameters for ListInviteLinks.
type ListInviteLinksParamsStatus string

// CreateInviteLinkParams defines parameters for CreateInviteLink.
type CreateInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateIntroductionParams defines parameters for CreateIntroduction.
type CreateIntroductionParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListMyTeamsParams defines parameters for ListMyTeams.
type ListMyTeamsParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateCodeJSONRequestBody defines body for CreateCode for application/json ContentType.
type CreateCodeJSONRequestBody = CreateCodeRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshSessionRequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// CreateInviteLinkJSONRequestBody defines body for CreateInviteLink for application/json ContentType.
type CreateInviteLinkJSONRequestBody = CreateInviteLinkRequest

// CreateIntroductionJSONRequestBody defines body for CreateIntroduction for application/json ContentType.
type CreateIntroductionJSONRequestBody = CreateIntroductionRequest

// AsActiveInviteLinkState returns the union data inside the InviteLinkState as a ActiveInviteLinkState
func (t InviteLinkState) AsActiveInviteLinkState() (ActiveInviteLinkState, error) {
	var body ActiveInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActiveInviteLinkState overwrites any union data inside the InviteLinkState as the provided ActiveInviteLinkState
func (t *InviteLinkState) FromActiveInviteLinkState(v ActiveInviteLinkState) error {
	v.Status = "active"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActiveInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided ActiveInviteLinkState
func (t *InviteLinkState) MergeActiveInviteLinkState(v ActiveInviteLinkState) error {
	v.Status = "active"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExpiredInviteLinkState returns the union data inside the InviteLinkState as a ExpiredInviteLinkState
func (t InviteLinkState) AsExpiredInviteLinkState() (ExpiredInviteLinkState, error) {
	var body ExpiredInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExpiredInviteLinkState overwrites any union data inside the InviteLinkState as the provided ExpiredInviteLinkState
func (t *InviteLinkState) FromExpiredInviteLinkState(v ExpiredInviteLinkState) error {
	v.Status = "expired"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExpiredInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided ExpiredInviteLinkState
func (t *InviteLinkState) MergeExpiredInviteLinkState(v ExpiredInviteLinkState) error {
	v.Status = "expired"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRevokedInviteLinkState returns the union data inside the InviteLinkState as a RevokedInviteLinkState
func (t InviteLinkState) AsRevokedInviteLinkState() (RevokedInviteLinkState, error) {
	var body RevokedInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRevokedInviteLinkState overwrites any union data inside the InviteLinkState as the provided RevokedInviteLinkState
func (t *InviteLinkState) FromRevokedInviteLinkState(v RevokedInviteLinkState) error {
	v.Status = "revoked"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRevokedInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided RevokedInviteLinkState
func (t *InviteLinkState) MergeRevokedInviteLinkState(v RevokedInviteLinkState) error {
	v.Status = "revoked"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InviteLinkState) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t InviteLinkState) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "active":
		return t.AsActiveInviteLinkState()
	case "expired":
		return t.AsExpiredInviteLinkState()
	case "revoked":
		return t.AsRevokedInviteLinkState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t InviteLinkState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InviteLinkState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUnintroducedUserState returns the union data inside the UserState as a UnintroducedUserState
func (t UserState) AsUnintroducedUserState() (UnintroducedUserState, error) {
	var body UnintroducedUserState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnintroducedUserState overwrites any union data inside the UserState as the provided UnintroducedUserState
func (t *UserState) FromUnintroducedUserState(v UnintroducedUserState) error {
	v.Status = "unintroduced"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnintroducedUserState performs a merge with any union data inside the UserState, using the provided UnintroducedUserState
func (t *UserState) MergeUnintroducedUserState(v UnintroducedUserState) error {
	v.Status = "unintroduced"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIntroducedUserState returns the union data inside the UserState as a IntroducedUserState
func (t UserState) AsIntroducedUserState() (IntroducedUserState, error) {
	var body IntroducedUserState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIntroducedUserState overwrites any union data inside the UserState as the provided IntroducedUserState
func (t *UserState) FromIntroducedUserState(v IntroducedUserState) error {
	v.Status = "introduced"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIntroducedUserState performs a merge with any union data inside the UserState, using the provided IntroducedUserState
func (t *UserState) MergeIntroducedUserState(v IntroducedUserState) error {
	v.Status = "introduced"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UserState) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UserState) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "introduced":
		return t.AsIntroducedUserState()
	case "unintroduced":
		return t.AsUnintroducedUserState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UserState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UserState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request a sign-in code
	// (POST /auth/codes)
	CreateCode(w http.ResponseWriter, r *http.Request)
	// Sign in with a code
	// (POST /auth/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Sign out
	// (DELETE /auth/sessions/current)
	DeleteSession(w http.ResponseWriter, r *http.Request)
	// Trade the refresh token for a fresh pass
	// (POST /auth/sessions/current/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request)
	// Revoke an invite link
	// (DELETE /invite-links/{code})
	RevokeInviteLink(w http.ResponseWriter, r *http.Request, code string, params RevokeInviteLinkParams)
	// Join a team via an invite link
	// (POST /invite-links/{code}/acceptances)
	AcceptInviteLink(w http.ResponseWriter, r *http.Request, code string, params AcceptInviteLinkParams)
	// Create a team
	// (POST /teams)
	CreateTeam(w http.ResponseWriter, r *http.Request, params CreateTeamParams)
	// Get a team
	// (GET /teams/{id})
	GetTeam(w http.ResponseWriter, r *http.Request, id string, params GetTeamParams)
	// List the team's invite links
	// (GET /teams/{team_id}/invite-links)
	ListInviteLinks(w http.ResponseWriter, r *http.Request, teamId string, params ListInviteLinksParams)
	// Create an invite link
	// (POST /teams/{team_id}/invite-links)
	CreateInviteLink(w http.ResponseWriter, r *http.Request, teamId string, params CreateInviteLinkParams)
	// Get the caller
	// (GET /users/me)
	GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams)
	// Introduce yourself
	// (POST /users/me/introduction)
	CreateIntroduction(w http.ResponseWriter, r *http.Request, params CreateIntroductionParams)
	// List the caller's teams
	// (GET /users/me/teams)
	ListMyTeams(w http.ResponseWriter, r *http.Request, params ListMyTeamsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCode operation middleware
func (siw *ServerInterfaceWrapper) CreateCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeInviteLink operation middleware
func (siw *ServerInterfaceWrapper) RevokeInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeInviteLink(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInviteLink operation middleware
func (siw *ServerInterfaceWrapper) AcceptInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AcceptInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInviteLink(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTeamParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeam(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInviteLinks operation middleware
func (siw *ServerInterfaceWrapper) ListInviteLinks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "team_id" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "team_id", r.PathValue("team_id"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInviteLinksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInviteLinks(w, r, teamId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInviteLink operation middleware
func (siw *ServerInterfaceWrapper) CreateInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "team_id" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "team_id", r.PathValue("team_id"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInviteLink(w, r, teamId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMeParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIntroduction operation middleware
func (siw *ServerInterfaceWrapper) CreateIntroduction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateIntroductionParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIntroduction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyTeams operation middleware
func (siw *ServerInterfaceWrapper) ListMyTeams(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyTeamsParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyTeams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/codes", wrapper.CreateCode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/sessions/current", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/sessions/current/refresh", wrapper.RefreshSession)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/invite-links/{code}", wrapper.RevokeInviteLink)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/invite-links/{code}/acceptances", wrapper.AcceptInviteLink)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teams", wrapper.CreateTeam)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teams/{id}", wrapper.GetTeam)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teams/{team_id}/invite-links", wrapper.ListInviteLinks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teams/{team_id}/invite-links", wrapper.CreateInviteLink)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users/me/introduction", wrapper.CreateIntroduction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me/teams", wrapper.ListMyTeams)

	return m
}

type CreateCodeRequestObject struct {
	Body *CreateCodeJSONRequestBody
}

type CreateCodeResponseObject interface {
	VisitCreateCodeResponse(w http.ResponseWriter) error
}

type CreateCode202JSONResponse CodeDelivery

func (response CreateCode202JSONResponse) VisitCreateCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCode400ApplicationProblemPlusJSONResponse Problem

func (response CreateCode400ApplicationProblemPlusJSONResponse) VisitCreateCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCode429ResponseHeaders struct {
	RetryAfter *int
}

type CreateCode429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers CreateCode429ResponseHeaders
}

func (response CreateCode429ApplicationProblemPlusJSONResponse) VisitCreateCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCode500ApplicationProblemPlusJSONResponse Problem

func (response CreateCode500ApplicationProblemPlusJSONResponse) VisitCreateCodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Pass

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession400ApplicationProblemPlusJSONResponse Problem

func (response CreateSession400ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession401ApplicationProblemPlusJSONResponse InvalidCodeProblem

func (response CreateSession401ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession410ApplicationProblemPlusJSONResponse Problem

func (response CreateSession410ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession500ApplicationProblemPlusJSONResponse Problem

func (response CreateSession500ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession401ApplicationProblemPlusJSONResponse Problem

func (response DeleteSession401ApplicationProblemPlusJSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSession500ApplicationProblemPlusJSONResponse Problem

func (response DeleteSession500ApplicationProblemPlusJSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSessionRequestObject struct {
	Body *RefreshSessionJSONRequestBody
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200JSONResponse Pass

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession400ApplicationProblemPlusJSONResponse Problem

func (response RefreshSession400ApplicationProblemPlusJSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession401ApplicationProblemPlusJSONResponse Problem

func (response RefreshSession401ApplicationProblemPlusJSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession500ApplicationProblemPlusJSONResponse Problem

func (response RefreshSession500ApplicationProblemPlusJSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLinkRequestObject struct {
	Code   string `json:"code"`
	Params RevokeInviteLinkParams
}

type RevokeInviteLinkResponseObject interface {
	VisitRevokeInviteLinkResponse(w http.ResponseWriter) error
}

type RevokeInviteLink204Response struct {
}

func (response RevokeInviteLink204Response) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink400ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink403ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink404ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink404ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink409ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink409ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink500ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLinkRequestObject struct {
	Code   string `json:"code"`
	Params AcceptInviteLinkParams
}

type AcceptInviteLinkResponseObject interface {
	VisitAcceptInviteLinkResponse(w http.ResponseWriter) error
}

type AcceptInviteLink200JSONResponse Team

func (response AcceptInviteLink200JSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink201JSONResponse Team

func (response AcceptInviteLink201JSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink400ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink401ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink401ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink403ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink404ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink404ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink410ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink410ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink500ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeamRequestObject struct {
	Params CreateTeamParams
	Body   *CreateTeamJSONRequestBody
}

type CreateTeamResponseObject interface {
	VisitCreateTeamResponse(w http.ResponseWriter) error
}

type CreateTeam201ResponseHeaders struct {
	Location *string
}

type CreateTeam201JSONResponse struct {
	Body    Team
	Headers CreateTeam201ResponseHeaders
}

func (response CreateTeam201JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam400ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam400ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam401ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam401ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam403ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam403ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam500ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam500ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeamRequestObject struct {
	Id     string `json:"id"`
	Params GetTeamParams
}

type GetTeamResponseObject interface {
	VisitGetTeamResponse(w http.ResponseWriter) error
}

type GetTeam200JSONResponse Team

func (response GetTeam200JSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam400ApplicationProblemPlusJSONResponse Problem

func (response GetTeam400ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam403ApplicationProblemPlusJSONResponse Problem

func (response GetTeam403ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam404ApplicationProblemPlusJSONResponse Problem

func (response GetTeam404ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam500ApplicationProblemPlusJSONResponse Problem

func (response GetTeam500ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinksRequestObject struct {
	TeamId string `json:"team_id"`
	Params ListInviteLinksParams
}

type ListInviteLinksResponseObject interface {
	VisitListInviteLinksResponse(w http.ResponseWriter) error
}

type ListInviteLinks200JSONResponse []InviteLink

func (response ListInviteLinks200JSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks400ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks400ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks403ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks403ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks500ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks500ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLinkRequestObject struct {
	TeamId string `json:"team_id"`
	Params CreateInviteLinkParams
	Body   *CreateInviteLinkJSONRequestBody
}

type CreateInviteLinkResponseObject interface {
	VisitCreateInviteLinkResponse(w http.ResponseWriter) error
}

type CreateInviteLink201JSONResponse InviteLink

func (response CreateInviteLink201JSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink400ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink403ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink500ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
	Params GetMeParams
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe400ApplicationProblemPlusJSONResponse Problem

func (response GetMe400ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse Problem

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500ApplicationProblemPlusJSONResponse Problem

func (response GetMe500ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroductionRequestObject struct {
	Params CreateIntroductionParams
	Body   *CreateIntroductionJSONRequestBody
}

type CreateIntroductionResponseObject interface {
	VisitCreateIntroductionResponse(w http.ResponseWriter) error
}

type CreateIntroduction201JSONResponse User

func (response CreateIntroduction201JSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction400ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction400ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction401ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction401ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction409ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction409ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction500ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction500ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeamsRequestObject struct {
	Params ListMyTeamsParams
}

type ListMyTeamsResponseObject interface {
	VisitListMyTeamsResponse(w http.ResponseWriter) error
}

type ListMyTeams200JSONResponse []Team

func (response ListMyTeams200JSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams400ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams400ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams403ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams403ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams500ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams500ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Request a sign-in code
	// (POST /auth/codes)
	CreateCode(ctx context.Context, request CreateCodeRequestObject) (CreateCodeResponseObject, error)
	// Sign in with a code
	// (POST /auth/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Sign out
	// (DELETE /auth/sessions/current)
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// Trade the refresh token for a fresh pass
	// (POST /auth/sessions/current/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// Revoke an invite link
	// (DELETE /invite-links/{code})
	RevokeInviteLink(ctx context.Context, request RevokeInviteLinkRequestObject) (RevokeInviteLinkResponseObject, error)
	// Join a team via an invite link
	// (POST /invite-links/{code}/acceptances)
	AcceptInviteLink(ctx context.Context, request AcceptInviteLinkRequestObject) (AcceptInviteLinkResponseObject, error)
	// Create a team
	// (POST /teams)
	CreateTeam(ctx context.Context, request CreateTeamRequestObject) (CreateTeamResponseObject, error)
	// Get a team
	// (GET /teams/{id})
	GetTeam(ctx context.Context, request GetTeamRequestObject) (GetTeamResponseObject, error)
	// List the team's invite links
	// (GET /teams/{team_id}/invite-links)
	ListInviteLinks(ctx context.Context, request ListInviteLinksRequestObject) (ListInviteLinksResponseObject, error)
	// Create an invite link
	// (POST /teams/{team_id}/invite-links)
	CreateInviteLink(ctx context.Context, request CreateInviteLinkRequestObject) (CreateInviteLinkResponseObject, error)
	// Get the caller
	// (GET /users/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Introduce yourself
	// (POST /users/me/introduction)
	CreateIntroduction(ctx context.Context, request CreateIntroductionRequestObject) (CreateIntroductionResponseObject, error)
	// List the caller's teams
	// (GET /users/me/teams)
	ListMyTeams(ctx context.Context, request ListMyTeamsRequestObject) (ListMyTeamsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateCode operation middleware
func (sh *strictHandler) CreateCode(w http.ResponseWriter, r *http.Request) {
	var request CreateCodeRequestObject

	var body CreateCodeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCode(ctx, request.(CreateCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCodeResponseObject); ok {
		if err := validResponse.VisitCreateCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(w http.ResponseWriter, r *http.Request) {
	var request RefreshSessionRequestObject

	var body RefreshSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeInviteLink operation middleware
func (sh *strictHandler) RevokeInviteLink(w http.ResponseWriter, r *http.Request, code string, params RevokeInviteLinkParams) {
	var request RevokeInviteLinkRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeInviteLink(ctx, request.(RevokeInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeInviteLinkResponseObject); ok {
		if err := validResponse.VisitRevokeInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptInviteLink operation middleware
func (sh *strictHandler) AcceptInviteLink(w http.ResponseWriter, r *http.Request, code string, params AcceptInviteLinkParams) {
	var request AcceptInviteLinkRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptInviteLink(ctx, request.(AcceptInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptInviteLinkResponseObject); ok {
		if err := validResponse.VisitAcceptInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTeam operation middleware
func (sh *strictHandler) CreateTeam(w http.ResponseWriter, r *http.Request, params CreateTeamParams) {
	var request CreateTeamRequestObject

	request.Params = params

	var body CreateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTeam(ctx, request.(CreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTeamResponseObject); ok {
		if err := validResponse.VisitCreateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTeam operation middleware
func (sh *strictHandler) GetTeam(w http.ResponseWriter, r *http.Request, id string, params GetTeamParams) {
	var request GetTeamRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeam(ctx, request.(GetTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTeamResponseObject); ok {
		if err := validResponse.VisitGetTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInviteLinks operation middleware
func (sh *strictHandler) ListInviteLinks(w http.ResponseWriter, r *http.Request, teamId string, params ListInviteLinksParams) {
	var request ListInviteLinksRequestObject

	request.TeamId = teamId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInviteLinks(ctx, request.(ListInviteLinksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInviteLinks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInviteLinksResponseObject); ok {
		if err := validResponse.VisitListInviteLinksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInviteLink operation middleware
func (sh *strictHandler) CreateInviteLink(w http.ResponseWriter, r *http.Request, teamId string, params CreateInviteLinkParams) {
	var request CreateInviteLinkRequestObject

	request.TeamId = teamId
	request.Params = params

	var body CreateInviteLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInviteLink(ctx, request.(CreateInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInviteLinkResponseObject); ok {
		if err := validResponse.VisitCreateInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams) {
	var request GetMeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIntroduction operation middleware
func (sh *strictHandler) CreateIntroduction(w http.ResponseWriter, r *http.Request, params CreateIntroductionParams) {
	var request CreateIntroductionRequestObject

	request.Params = params

	var body CreateIntroductionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIntroduction(ctx, request.(CreateIntroductionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIntroduction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateIntroductionResponseObject); ok {
		if err := validResponse.VisitCreateIntroductionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyTeams operation middleware
func (sh *strictHandler) ListMyTeams(w http.ResponseWriter, r *http.Request, params ListMyTeamsParams) {
	var request ListMyTeamsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyTeams(ctx, request.(ListMyTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyTeamsResponseObject); ok {
		if err := validResponse.VisitListMyTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hzbktw2kvarIPg7wjP/Ut2tg3dHtVeyrJnpDVlW6BCeCFkro8isItwgQANglTjajtiH2CfcJ9nITICH",
	"KlZ1a3Rw78pXanWDBJDI/PLLA/guK2zdWAMm+GzxLmukkzUEcPS/v7304M5L/LEEXzjVBGVNtsheQN1Y",
	"J10nGi0LqKwuwYnWBKWFA6mFbEMFJqhC4hMC3iof/Ik4L/GXKwVehApEIbUGd/KTyfJM4XsrkCW4LM+M",
	"rCFbZH+7hSu4dV5meebg11Y5KLNFcC3kmS8qqCWubWVdLUO2yNpW4cjQNfiwD06ZdXZ5eZkG06YeFEFt",
	"4NxsVIDHylw8DzIA7d3ZBlxQQMPgbaMc+Df44tEUpQxwK6gacJGt1nKpIa1oZ94880GGlt9m2jpbvMok",
	"TZ693l/keIOv0pP5eBnDQ3b5CxQBZ3hoS167DAEcivDfX53duv/63T9ffpXNrAjHfwdabcB1+8f6XHZ4",
	"MDIIKQpbgthKLzyYcCLOgyikc3hyBlSowPEJ4ihj+T+yLB14L6wRTesa62ExDFqCtmbthTL0u1oqvbRv",
	"cyFNOXlYebHFFQz6ISrpxS+tD8K3TaMVlKwx731ee9JwEFz3Rq4CuBlhQGFN6cUSVtaBkMbSrmkztezE",
	"EgSeGPgApViRCJRP2zgZplMmwBrc3hGPFjxdyew5O5AB8PSe8ZwzCosixR++crDKFtn/Ox1M+zTq/+kj",
	"GrS3FPrt4XnPTXC2bAuUzMH5Ww+Ozfb4El6mcbur6F9wbCHJakfLmB7bD7UKQZm1GOQrCnrYCym0Mhes",
	"4QY24NKgj6NQlwfX/Ry8Pya7IprxMbmRqV/mH37OOU93WMovQNYHl3qdI8YXPJk74oPH+yhtqpdzWmst",
	"3z4Gsw5Vtrjzzb0ZI35E51ReE9DL9wKIfQCPb3lvBC8PIXiyLSjRMA6sfX8dqn9sZin5hxtjv/yjVnlu",
	"NlKrElXzqbNLDTVOKLX+YZUtXh2fOj1wme/uFn1Z3QT/RsOKDusKJJ2O31/na15pVI/D1rcnRcaN91eZ",
	"K8W+q6x8Ym8K25rrbJgWPH5kstS0hgMHtmslpUL4rJWRwZIbrGXT4GbwJJiuHNjFPJPqNf4gNs0bLG5x",
	"Yy8OP/eM/zwju3ic3RNmjVF3L/PMGriGJs7vA/XyKMTOb+Oqxw7tApX0qfR+hmxXIC4AmZkVUnh2Jbkw",
	"lklS/IVQwYNenQgcLosCuVSwF2CQUfnKunALaV/JhMvJDWgiYw/aUFmn/s5EHbk6csNEbfh1DlYOfDW8",
	"D6nc6HXLtkPnyoMaqZywpgCmdeOVlAr8vwoV8BX4R2tAbK0LlfABpFZmzXwwccVtBQ4Ey8KLQhrcswNZ",
	"VEKFOZ/Ns735R7hgfJQWOgsGUQg7L58e1fd2Ax7J4Fa6UmxVqHpx0sOL4QBJGGLlbC1K5VsPfKL0C7kG",
	"3t11aSyv7NDad+FyvNN8Rma7b5zd+xy6jHzAVC7P/vxQ3L/3zb+IOEJ8B0EqTaISf33x4ql48PR8loWV",
	"NHD2QJTxQZoCpiGgU8cd+S605llQQc/jP//iqrfviJdf1085J6dnLM6rWOF7nut0+Py8s9gzMzGN+0Cq",
	"lOD8+lRpNO/c8pFWznjvf8BJq/IaeYP8w7guvZLeMPHOhzb2JM414ru3z87yrFam///MEl8aNU8g931I",
	"A873uRjCWQxpKVTSHoRc2pY8So3wfGHs1ogOwol4mOJ+K3A74r//878IqqQRSLs6hHEELwNCBiG1zoW3",
	"HGT9NOKpBIc4haTX/JQlQF+C8FLNBvX7StWao8x3XrPmZI7C+qzKdC1iOBzhrDpdk+VNFeEIvxvJ8iBT",
	"3deufHoKh7Yyq5kfztYOvfcqxj3zzOsoq2TnU5t5bLfgCulBaAgBnM9FqdYq2k5rSnC+sA58Lu4iN7t7",
	"R9gVGVAesws+SBeI1YAp0dCsE6Vtl5p+5kTY8J5I3XRTySUQRzLSObud5NPYeNi61JBNLaRBO1I1Gzkq",
	"iViSZfLQGhxopCEe6qUGL1RgqoVGqQzSEmXWOpEttPWwtaKopJMF7r1/VBD9irkwbT2+Foxt1xUiRaOC",
	"1F5IR6Sx9VAKJ2O2UBqxsrqEcsAHXF+EpUp6+q9vQKN8GA5GaHj3zgQM7+aTpKe89fezW/df/yH98B9v",
	"0k9//P9fzfpsD0XrVOieo4aw9S9BOnDIiOcRdEJmmamJRnqfU5JUSC9+ntDphfiW3ih+as/O7hb0HP0I",
	"P5+IJ6QiUhTWXig6Wc5+kySCJViEIErQaglOBtAdCQ6nXCN37lOSXgVIYFrLCybeS2e3Hv8IpmSExuOW",
	"YltZDaLQ0ntU15V1azwk5iBe+GAbzz6iPwSyIZQey2eQZhVCw/l1ZVZ2X2YPLVq6RFWWwtk2KNRH6S8w",
	"ACkuwHHeFGTtWfl95wPUwkFhXemRO5vgxR+2lRWlKjkxTFpbgfkj/VRa8kwYFnirNyAKa1ZaFcEPqo0T",
	"8E4i1esX9uDpeZZnG3CeF3x2cnZym6CoASMblS2yuydnJ2cZKVtFSnIq21CdYgjOFRM7l4V8DqbETVvD",
	"foPTxsHS0azVBkyfKWarN34LLsVFHk18WwGdrnXJ28qCon0htQNZdsmTL6FSlERH4fBLFyKwFdHr0JJl",
	"I10QW9vqUoTWGc5WK0MxZakcFMG6DjXCwVr5AA5K0YBtdMQl3kCMG5cdJfCFNbqjY0CwIn2maexKSENo",
	"01jjYyxDEkfxnKPLGBLasbQDPnxry47zMSYAJ0Jk0+hYRDr9xVtiwUPh52i6dC9jfjl1qcG1QL/gRdJh",
	"3jm78/EWMC610Nz7gLJTZHkS+RiHvbLzvRKMTp9PPZ8QOHqgcbZWPpbW6HiQuGGMjoytjEsZYm/yB1KL",
	"AD46A/Rttg2FrYd6TdTZvl5DaQcbix2ktXi8l3l27+zsiOwaDvz+6f1k2OcI58U3qhnhsnwlGyiFVhfA",
	"5JRkkMzsB9ww7hCZGj5SVFBcQEnCW/SSpocKkndopWYhUcIhTYPUWKInTITWs3cfalkOfKvJDOKf8NEx",
	"kEfEaqwLXM1C+d25/1nlZ62o0UoJyY6VssSPcZ/0W61qxYknMGVjlUECjxqDcLeVHSoHC9506M8dNMRZ",
	"dcfFwAjxhNucvhoJz9saKClU2Ygn0uMR9aMdFKA2vWdij0mm+wyC6249OF7LC1ZspQqpphc3jQc0Lu9l",
	"4+LyXioWRfnN59X1c4M8R2rhwVHVyjnLWWHf1rV0XbbIIsoRk1ubW8qkrQS59pT2QVrzGh9iDxbzUEec",
	"2KO3RSXNGk82WhOUDFmoI0x9+nwjYRPrAXmVJfTApFaTCm8lS4oWF7RSsg7Dpx//2zZEICmgLEKO+iVb",
	"j6rSSHQh7Nbq6M1qkAbBEn+djHinoEzBbDJPGUY1ZuWRA0SuSvrhZTdyeCOYCHbNL6e03mSGQBiuvG+j",
	"/SDgevW2jxcckMW3Rv3aJiammZxDl3g8osLSlt1hdxkTRp/UY+4kpa7lNG9/tDVQBnzGAp6rtYFSKDOh",
	"Sz3587Kbnn3URzyWpXWG2weM3S56BZCC4ue8T2Ug10xuEAcgx2KSH/rkyShHS7pT2xod92/iAGPtLYEY",
	"r+D2R1/BTInvGJnpj6SWoaj6LP/INqa+pX/Qt26jNgTzyrOriKdMRKiyW3ZXqdiHp4SRkoZVj+eMOcvW",
	"mcGr3v6sh/LECqRZcUtBcgNJ5OfjfZ8HaiKp5AZiE0KJQAcGA2AT4s+8FaTbK0bftPscwwIa4oBasGiQ",
	"FAZQYihxhCCptVjZ1lEjTRR+jC6IN+Z90QbXG8Ny6Hq8ClaXHDlEad5Av4fIgA6EUFle1+mdFq1zcQsl",
	"aJjLmT4ixjCqsBEOOECuTv7gAk+op8k5Z3SI6W1UERk2HgMZAWET/wXBJ2Y9lCevR9CGz6On6lm9XQk1",
	"W4Gj0lHvhvqKoLf9ozEf5AAVopwvCjIHpR4rLuNdADRebK27IC9M3XwqpB6ZRVQg60GsYCtqZdoQaVlD",
	"2YQ2aLJg8q0qCAyi/Yl4Ht06UcgtSiZOjqiLJ9oLyRNNS0ouVgpPIG2JDD1YpJ3sQAkdxgGznHWd39Hx",
	"jl3nxHfdm2GLfCK2/WSgelVcM3NS+Lsm9Mkz4lWUk++10yJ0yAthVzfOWmOqjXK74yTbq9eXr/eMGeV+",
	"fQs+jaZxmMaeo+/xCI1cRu9x8FpmHRNTkyL7YD2MvQvUdi19iAXdEa9lK/KDCfRRoofIcmNYimvjyXgJ",
	"w5LSYZNnSA2UsgiM8clqkCFz/pnNAZ0AcmNPqNh0XLe3HvoVmIkYKGOFsqGKNT5dWc3Ba8g5+FLrKqxa",
	"LezWgBPKFLotUzfm1OimFc5PRFjny6jXYqxnn5yx/jk2Q/gUGPzfpYhXoNksjJ2IlyaGZT39ieVfZDIT",
	"g8FgM6Y82QQm3Ea6xBTRjWl1AUPEiFobm9PRI5aWzY0jLwr7qeiJvLIv3fhIKORaKpP6UeLrhqRqPcmo",
	"VqAbsa0spSxwQo4vrAZDtndz6dMLJ0uIqZUxxeAIf9Ur8TwiK+okuKWVufCn75B7XR5jVN9Ld8EOmx/k",
	"dlzp08nHJB3xJYKYiGcBZC0obdPnJJE881N9K9AuAuEfR21/+eRyw6t3fOOgkaEa7hsUQz56/qrBXhlp",
	"/nCGmU7THQp0dFdTj/ORXFL/xA3BjbufGzdi938Ejj2lQBl97Uk3CCIwGMSBo44DtFMPGjkpdyb0TFNT",
	"6ZDTsoUqMTRVzlPYRZFkmiA6TUSltunj/Huf+TB6laDsg21NVIr7n/tIxmaL0WxE5ZGm3sjMKMGENOPl",
	"j/BsDGKHce2UPZc0xbG634OyHF9tQmyTooZ6uQNmuxg45psPaKJYNVAl1I1FWS4m2fGR9PsJ8HeeYjdE",
	"bxzNTo4rg3E0eacURHBiwLdFAVByX0NK+cawK2ZoeDd16wOnLOaNjGwoslLapgdqNfBxhVQ4RKidA2ze",
	"9o0G7I/HGqmVbUafH+ye6UhppgE+HVOM7CMUIkUZ8p4UoEjlObHEBEYFHuBjaZdU6RerzE6fRlCUx+cX",
	"YRjf59M+ZrL3kBD+jReU9v3FEudodQVRzNgp1/f8lL+tVz7ubTuIcS6Hv5RULCdpi4hMVvjKbgdcHJoQ",
	"b5qzvX32WzpbY6nnHhyl5/yJ+DFWO6KNptAJcV/Vje5SVJXoU8kNPa3yFZQLEa9wbmXXs3yajm8BUDcH",
	"UKcWd9uoouqRaGuHgtdwcETNviZqDm8bTaET0zYusX3tb24MhHiTPNZGyfdiCtS8dJgPPOxvHrJ6m5I6",
	"tCYcgbouUHzv72sX6cVojtHH5r2zxcgYzYtyg1RN5SL3Tq190pabDHtsnocLkoTge376vRzsp6pjji8x",
	"fuYi5iG/hr+Pd1HLafPCY8sT7SvQy2ePk+XFJ9knzt9/n72ecPm7//xy/ecNhFu2z4hcI3RlKB3B6uk7",
	"VVI+aQ0z0PoMQutMD61LzqKr2XT0XyDMQ9VMSKE+7GMTNzzAIAwapRC+3LzSlRaI7lj5cY5olBzilOQo",
	"OUTRmQrcrZDsk81x3JlCz8XPofwmDJcUoKe2lDkLe8m2FH7eUAT5C4RrwQf+80aVl5N8zpWAMuJ+Q7Ew",
	"phlpLHWFrpTmJullJ/gKyyh7jaO/jqyOUtVa+QGWd9HpsfKjvIe/FkrFrX0oVNGbf23BdcOr++t4w5t2",
	"Pl8zXPHOj97y+3xQqAIwDb/erfvhcmcmnZPdFaGg/9KxElWY+uwAOKKLCj42lSEm7XGubwYjwMvHQNP/",
	"iTOfyGRUiF1NfZEH48wYndgtV9TDbCv1JLodrhelEMe2wasyUY50VUaDpHsQ3KySPlH1nY2lfVmOm9yF",
	"9KJxlqh4/DpRcgEOpD4RD0w09y11yPRRmbFTQFlD8MPVSU1ySYHyiXiQ5LOt7BUeimbmK1ZEC4O1+fCx",
	"olTQRBe0gZGnkje4l+txRMk59TochudXxt7DV39iXxRJLXDqs5/wGH5z7IVB9OFg+D1T1x8JwW9EsL3/",
	"XabLGHN/ohB7DOXHs3gp3v4dwQlLoiLPcJyI6l86jH/RAJxC8/dIgLYeYYbvT8/S6h8ruxNhxBucScli",
	"FzTC4lwIBtyoP23JJ4GPK1bKrMAhHQftYctXulQYelLxQOIVZ27a379wRLeZ48cImybdzzayRo31haPm",
	"7KC0Ht3Q5etJ1Cp0IO/wPXxggvQTJQjo+wdzNy1aaj5dtbq/v/l7Ae5gAvGGBseDvY2Mlyx1x2pP1ejT",
	"jofLGE9knTq9uW89hcVc8Q+qhhPxMuYqlReVbBowXkhdWx+4o5QzIsr3dkawUPefNEiXsqhE4THU2EmB",
	"cuoz3pqazYMi7Ef3Mm00F7XUyKWGm+5i2aa7cr3viB+2EmW6P1GBKUDcO7s/gZp7Z2fHSOBInjezMjL3",
	"Nc/PXCE5BD7DVzp+x5wjRYvP2vf1KH3tV/lk/X0vEbU3ofX2eUQyZfaKqykLTK4WHfSJ+NaGigqU0+81",
	"pGt5bJPxAwdj49szZO5lWtLrIsWjC+BovwwdUSICgycf78Qzid1aV8Y+/Z/5Q2M/D3dDQWs/6vS9uaSt",
	"NxrR2dZ50KurQL8vWh/Ng9Ko+A2+na8x8/V4tYFUa65Uk5PcqAM6VKCccFZjoEEBAbkBBwWYoLvUcUTO",
	"Ayk3UXC636P6es4adWW4aakVDv2r3OB5GRsX1+P7SirdOmBUN4LOVbou3fEc3xdiNRsnYA7lZL/vXpCg",
	"fjP+dq2s5ovYInVVPvMhHV/smPW/V3+uUf1BLabMPXf5LyEqDd1X7wR9G4q7HRH2NPgeIWNsSoFN1HZp",
	"IgXCJ5ZcpR1990VyMCn1BO52EoXj7ya5VoNYtzJ+KMd1orQ2ot//ghRfMVXHmToOXRzDF7HR7X6cq5Ba",
	"lLABbRuM57I8a52OHyVanJ5qHFBZHxZ/OvvT2enmNpljnGTuxh87giE/R9ccLvPdoU+pcXIYxgC7Py5B",
	"xyjbNzfsfJriTDXocZx9+fryfwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
