//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActiveInviteLinkStateStatus.
const (
	ActiveInviteLinkStateStatusActive ActiveInviteLinkStateStatus = "active"
)

// Valid indicates whether the value is a known member of the ActiveInviteLinkStateStatus enum.
func (e ActiveInviteLinkStateStatus) Valid() bool {
	switch e {
	case ActiveInviteLinkStateStatusActive:
		return true
	default:
		return false
	}
}

// Defines values for ExpiredInviteLinkStateStatus.
const (
	Expired ExpiredInviteLinkStateStatus = "expired"
)

// Valid indicates whether the value is a known member of the ExpiredInviteLinkStateStatus enum.
func (e ExpiredInviteLinkStateStatus) Valid() bool {
	switch e {
	case Expired:
		return true
	default:
		return false
	}
}

// Defines values for IntroducedUserStateStatus.
const (
	Introduced IntroducedUserStateStatus = "introduced"
)

// Valid indicates whether the value is a known member of the IntroducedUserStateStatus enum.
func (e IntroducedUserStateStatus) Valid() bool {
	switch e {
	case Introduced:
		return true
	default:
		return false
	}
}

// Defines values for RevokedInviteLinkStateStatus.
const (
	Revoked RevokedInviteLinkStateStatus = "revoked"
)

// Valid indicates whether the value is a known member of the RevokedInviteLinkStateStatus enum.
func (e RevokedInviteLinkStateStatus) Valid() bool {
	switch e {
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for UnintroducedUserStateStatus.
const (
	Unintroduced UnintroducedUserStateStatus = "unintroduced"
)

// Valid indicates whether the value is a known member of the UnintroducedUserStateStatus enum.
func (e UnintroducedUserStateStatus) Valid() bool {
	switch e {
	case Unintroduced:
		return true
	default:
		return false
	}
}

// Defines values for ListInviteLinksParamsStatus.
const (
	ListInviteLinksParamsStatusActive  ListInviteLinksParamsStatus = "active"
	ListInviteLinksParamsStatusExpired ListInviteLinksParamsStatus = "expired"
	ListInviteLinksParamsStatusRevoked ListInviteLinksParamsStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ListInviteLinksParamsStatus enum.
func (e ListInviteLinksParamsStatus) Valid() bool {
	switch e {
	case ListInviteLinksParamsStatusActive:
		return true
	case ListInviteLinksParamsStatusExpired:
		return true
	case ListInviteLinksParamsStatusRevoked:
		return true
	default:
		return false
	}
}

// ActiveInviteLinkState defines model for ActiveInviteLinkState.
type ActiveInviteLinkState struct {
	ExpiresAt *string                     `json:"expires_at"`
	Status    ActiveInviteLinkStateStatus `json:"status"`
}

// ActiveInviteLinkStateStatus defines model for ActiveInviteLinkState.Status.
type ActiveInviteLinkStateStatus string

// CreateIntroductionRequest defines model for CreateIntroductionRequest.
type CreateIntroductionRequest struct {
	// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
	Username Username `json:"username"`
}

// CreateInviteLinkRequest Omitting expires_at creates a link that never expires.
type CreateInviteLinkRequest struct {
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name TeamName `json:"name"`
}

// ExpiredInviteLinkState defines model for ExpiredInviteLinkState.
type ExpiredInviteLinkState struct {
	ExpiredAt string                       `json:"expired_at"`
	Status    ExpiredInviteLinkStateStatus `json:"status"`
}

// ExpiredInviteLinkStateStatus defines model for ExpiredInviteLinkState.Status.
type ExpiredInviteLinkStateStatus string

// IntroducedUserState defines model for IntroducedUserState.
type IntroducedUserState struct {
	Status IntroducedUserStateStatus `json:"status"`

	// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
	Username Username `json:"username"`
}

// IntroducedUserStateStatus defines model for IntroducedUserState.Status.
type IntroducedUserStateStatus string

// InviteLink defines model for InviteLink.
type InviteLink struct {
	Code      string          `json:"code"`
	CreatedAt string          `json:"created_at"`
	State     InviteLinkState `json:"state"`
	UseCount  int             `json:"use_count"`
}

// InviteLinkState defines model for InviteLinkState.
type InviteLinkState struct {
	union json.RawMessage
}

// Problem RFC 9457 Problem Details for HTTP APIs.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// RevokedInviteLinkState defines model for RevokedInviteLinkState.
type RevokedInviteLinkState struct {
	RevokedAt string                       `json:"revoked_at"`
	Status    RevokedInviteLinkStateStatus `json:"status"`
}

// RevokedInviteLinkStateStatus defines model for RevokedInviteLinkState.Status.
type RevokedInviteLinkStateStatus string

// Team defines model for Team.
type Team struct {
	CreatedAt string   `json:"created_at"`
	Id        string   `json:"id"`
	Name      TeamName `json:"name"`
}

// TeamName defines model for TeamName.
type TeamName = string

// UnintroducedUserState The person exists and nothing else about them is known yet. Carries no name — not an empty one, none at all, so that "introduced without a name" cannot be said.
type UnintroducedUserState struct {
	Status UnintroducedUserStateStatus `json:"status"`
}

// UnintroducedUserStateStatus defines model for UnintroducedUserState.Status.
type UnintroducedUserStateStatus string

// User defines model for User.
type User struct {
	CreatedAt string    `json:"created_at"`
	Id        string    `json:"id"`
	State     UserState `json:"state"`
}

// UserState defines model for UserState.
type UserState struct {
	union json.RawMessage
}

// Username Lowercase letters, digits and underscores, 3 to 32 of them, never starting, ending or doubling on the underscore. The alphabet is narrow on purpose: a name that identifies can be impersonated by one that merely resembles it, and within a single script no two characters resemble each other closely enough. Capitals are refused rather than folded, so that one person has one spelling.
type Username = string

// XUserId defines model for XUserId.
type XUserId = string

// RevokeInviteLinkParams defines parameters for RevokeInviteLink.
type RevokeInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// AcceptInviteLinkParams defines parameters for AcceptInviteLink.
type AcceptInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateTeamParams defines parameters for CreateTeam.
type CreateTeamParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// GetTeamParams defines parameters for GetTeam.
type GetTeamParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListInviteLinksParams defines parameters for ListInviteLinks.
type ListInviteLinksParams struct {
	Status *ListInviteLinksParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListInviteLinksParamsStatus defines parameters for ListInviteLinks.
type ListInviteLinksParamsStatus string

// CreateInviteLinkParams defines parameters for CreateInviteLink.
type CreateInviteLinkParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateIntroductionParams defines parameters for CreateIntroduction.
type CreateIntroductionParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// ListMyTeamsParams defines parameters for ListMyTeams.
type ListMyTeamsParams struct {
	// XUserId Temporary placeholder until real authentication exists. Identifies the caller.
	XUserId XUserId `json:"X-User-Id"`
}

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// CreateInviteLinkJSONRequestBody defines body for CreateInviteLink for application/json ContentType.
type CreateInviteLinkJSONRequestBody = CreateInviteLinkRequest

// CreateIntroductionJSONRequestBody defines body for CreateIntroduction for application/json ContentType.
type CreateIntroductionJSONRequestBody = CreateIntroductionRequest

// AsActiveInviteLinkState returns the union data inside the InviteLinkState as a ActiveInviteLinkState
func (t InviteLinkState) AsActiveInviteLinkState() (ActiveInviteLinkState, error) {
	var body ActiveInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActiveInviteLinkState overwrites any union data inside the InviteLinkState as the provided ActiveInviteLinkState
func (t *InviteLinkState) FromActiveInviteLinkState(v ActiveInviteLinkState) error {
	v.Status = "active"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActiveInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided ActiveInviteLinkState
func (t *InviteLinkState) MergeActiveInviteLinkState(v ActiveInviteLinkState) error {
	v.Status = "active"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExpiredInviteLinkState returns the union data inside the InviteLinkState as a ExpiredInviteLinkState
func (t InviteLinkState) AsExpiredInviteLinkState() (ExpiredInviteLinkState, error) {
	var body ExpiredInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExpiredInviteLinkState overwrites any union data inside the InviteLinkState as the provided ExpiredInviteLinkState
func (t *InviteLinkState) FromExpiredInviteLinkState(v ExpiredInviteLinkState) error {
	v.Status = "expired"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExpiredInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided ExpiredInviteLinkState
func (t *InviteLinkState) MergeExpiredInviteLinkState(v ExpiredInviteLinkState) error {
	v.Status = "expired"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRevokedInviteLinkState returns the union data inside the InviteLinkState as a RevokedInviteLinkState
func (t InviteLinkState) AsRevokedInviteLinkState() (RevokedInviteLinkState, error) {
	var body RevokedInviteLinkState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRevokedInviteLinkState overwrites any union data inside the InviteLinkState as the provided RevokedInviteLinkState
func (t *InviteLinkState) FromRevokedInviteLinkState(v RevokedInviteLinkState) error {
	v.Status = "revoked"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRevokedInviteLinkState performs a merge with any union data inside the InviteLinkState, using the provided RevokedInviteLinkState
func (t *InviteLinkState) MergeRevokedInviteLinkState(v RevokedInviteLinkState) error {
	v.Status = "revoked"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InviteLinkState) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t InviteLinkState) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "active":
		return t.AsActiveInviteLinkState()
	case "expired":
		return t.AsExpiredInviteLinkState()
	case "revoked":
		return t.AsRevokedInviteLinkState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t InviteLinkState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InviteLinkState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUnintroducedUserState returns the union data inside the UserState as a UnintroducedUserState
func (t UserState) AsUnintroducedUserState() (UnintroducedUserState, error) {
	var body UnintroducedUserState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnintroducedUserState overwrites any union data inside the UserState as the provided UnintroducedUserState
func (t *UserState) FromUnintroducedUserState(v UnintroducedUserState) error {
	v.Status = "unintroduced"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnintroducedUserState performs a merge with any union data inside the UserState, using the provided UnintroducedUserState
func (t *UserState) MergeUnintroducedUserState(v UnintroducedUserState) error {
	v.Status = "unintroduced"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIntroducedUserState returns the union data inside the UserState as a IntroducedUserState
func (t UserState) AsIntroducedUserState() (IntroducedUserState, error) {
	var body IntroducedUserState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIntroducedUserState overwrites any union data inside the UserState as the provided IntroducedUserState
func (t *UserState) FromIntroducedUserState(v IntroducedUserState) error {
	v.Status = "introduced"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIntroducedUserState performs a merge with any union data inside the UserState, using the provided IntroducedUserState
func (t *UserState) MergeIntroducedUserState(v IntroducedUserState) error {
	v.Status = "introduced"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UserState) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UserState) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "introduced":
		return t.AsIntroducedUserState()
	case "unintroduced":
		return t.AsUnintroducedUserState()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UserState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UserState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Revoke an invite link
	// (DELETE /invite-links/{code})
	RevokeInviteLink(w http.ResponseWriter, r *http.Request, code string, params RevokeInviteLinkParams)
	// Join a team via an invite link
	// (POST /invite-links/{code}/acceptances)
	AcceptInviteLink(w http.ResponseWriter, r *http.Request, code string, params AcceptInviteLinkParams)
	// Create a team
	// (POST /teams)
	CreateTeam(w http.ResponseWriter, r *http.Request, params CreateTeamParams)
	// Get a team
	// (GET /teams/{id})
	GetTeam(w http.ResponseWriter, r *http.Request, id string, params GetTeamParams)
	// List the team's invite links
	// (GET /teams/{team_id}/invite-links)
	ListInviteLinks(w http.ResponseWriter, r *http.Request, teamId string, params ListInviteLinksParams)
	// Create an invite link
	// (POST /teams/{team_id}/invite-links)
	CreateInviteLink(w http.ResponseWriter, r *http.Request, teamId string, params CreateInviteLinkParams)
	// Get the caller
	// (GET /users/me)
	GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams)
	// Introduce yourself
	// (POST /users/me/introduction)
	CreateIntroduction(w http.ResponseWriter, r *http.Request, params CreateIntroductionParams)
	// List the caller's teams
	// (GET /users/me/teams)
	ListMyTeams(w http.ResponseWriter, r *http.Request, params ListMyTeamsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RevokeInviteLink operation middleware
func (siw *ServerInterfaceWrapper) RevokeInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeInviteLink(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInviteLink operation middleware
func (siw *ServerInterfaceWrapper) AcceptInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AcceptInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInviteLink(w, r, code, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTeamParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeam(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInviteLinks operation middleware
func (siw *ServerInterfaceWrapper) ListInviteLinks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "team_id" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "team_id", r.PathValue("team_id"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInviteLinksParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInviteLinks(w, r, teamId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInviteLink operation middleware
func (siw *ServerInterfaceWrapper) CreateInviteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "team_id" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "team_id", r.PathValue("team_id"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateInviteLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInviteLink(w, r, teamId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMeParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIntroduction operation middleware
func (siw *ServerInterfaceWrapper) CreateIntroduction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateIntroductionParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIntroduction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyTeams operation middleware
func (siw *ServerInterfaceWrapper) ListMyTeams(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyTeamsParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId XUserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyTeams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/invite-links/{code}", wrapper.RevokeInviteLink)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/invite-links/{code}/acceptances", wrapper.AcceptInviteLink)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teams", wrapper.CreateTeam)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teams/{id}", wrapper.GetTeam)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teams/{team_id}/invite-links", wrapper.ListInviteLinks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teams/{team_id}/invite-links", wrapper.CreateInviteLink)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users/me/introduction", wrapper.CreateIntroduction)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me/teams", wrapper.ListMyTeams)

	return m
}

type RevokeInviteLinkRequestObject struct {
	Code   string `json:"code"`
	Params RevokeInviteLinkParams
}

type RevokeInviteLinkResponseObject interface {
	VisitRevokeInviteLinkResponse(w http.ResponseWriter) error
}

type RevokeInviteLink204Response struct {
}

func (response RevokeInviteLink204Response) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink400ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink403ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink404ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink404ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink409ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink409ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response RevokeInviteLink500ApplicationProblemPlusJSONResponse) VisitRevokeInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLinkRequestObject struct {
	Code   string `json:"code"`
	Params AcceptInviteLinkParams
}

type AcceptInviteLinkResponseObject interface {
	VisitAcceptInviteLinkResponse(w http.ResponseWriter) error
}

type AcceptInviteLink200JSONResponse Team

func (response AcceptInviteLink200JSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink201JSONResponse Team

func (response AcceptInviteLink201JSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink400ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink401ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink401ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink403ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink404ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink404ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink410ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink410ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response AcceptInviteLink500ApplicationProblemPlusJSONResponse) VisitAcceptInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeamRequestObject struct {
	Params CreateTeamParams
	Body   *CreateTeamJSONRequestBody
}

type CreateTeamResponseObject interface {
	VisitCreateTeamResponse(w http.ResponseWriter) error
}

type CreateTeam201ResponseHeaders struct {
	Location *string
}

type CreateTeam201JSONResponse struct {
	Body    Team
	Headers CreateTeam201ResponseHeaders
}

func (response CreateTeam201JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam400ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam400ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam401ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam401ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam403ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam403ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTeam500ApplicationProblemPlusJSONResponse Problem

func (response CreateTeam500ApplicationProblemPlusJSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeamRequestObject struct {
	Id     string `json:"id"`
	Params GetTeamParams
}

type GetTeamResponseObject interface {
	VisitGetTeamResponse(w http.ResponseWriter) error
}

type GetTeam200JSONResponse Team

func (response GetTeam200JSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam400ApplicationProblemPlusJSONResponse Problem

func (response GetTeam400ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam403ApplicationProblemPlusJSONResponse Problem

func (response GetTeam403ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam404ApplicationProblemPlusJSONResponse Problem

func (response GetTeam404ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTeam500ApplicationProblemPlusJSONResponse Problem

func (response GetTeam500ApplicationProblemPlusJSONResponse) VisitGetTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinksRequestObject struct {
	TeamId string `json:"team_id"`
	Params ListInviteLinksParams
}

type ListInviteLinksResponseObject interface {
	VisitListInviteLinksResponse(w http.ResponseWriter) error
}

type ListInviteLinks200JSONResponse []InviteLink

func (response ListInviteLinks200JSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks400ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks400ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks403ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks403ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInviteLinks500ApplicationProblemPlusJSONResponse Problem

func (response ListInviteLinks500ApplicationProblemPlusJSONResponse) VisitListInviteLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLinkRequestObject struct {
	TeamId string `json:"team_id"`
	Params CreateInviteLinkParams
	Body   *CreateInviteLinkJSONRequestBody
}

type CreateInviteLinkResponseObject interface {
	VisitCreateInviteLinkResponse(w http.ResponseWriter) error
}

type CreateInviteLink201JSONResponse InviteLink

func (response CreateInviteLink201JSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink400ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink400ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink403ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink403ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteLink500ApplicationProblemPlusJSONResponse Problem

func (response CreateInviteLink500ApplicationProblemPlusJSONResponse) VisitCreateInviteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
	Params GetMeParams
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe400ApplicationProblemPlusJSONResponse Problem

func (response GetMe400ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse Problem

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500ApplicationProblemPlusJSONResponse Problem

func (response GetMe500ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroductionRequestObject struct {
	Params CreateIntroductionParams
	Body   *CreateIntroductionJSONRequestBody
}

type CreateIntroductionResponseObject interface {
	VisitCreateIntroductionResponse(w http.ResponseWriter) error
}

type CreateIntroduction201JSONResponse User

func (response CreateIntroduction201JSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction400ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction400ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction401ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction401ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction409ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction409ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateIntroduction500ApplicationProblemPlusJSONResponse Problem

func (response CreateIntroduction500ApplicationProblemPlusJSONResponse) VisitCreateIntroductionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeamsRequestObject struct {
	Params ListMyTeamsParams
}

type ListMyTeamsResponseObject interface {
	VisitListMyTeamsResponse(w http.ResponseWriter) error
}

type ListMyTeams200JSONResponse []Team

func (response ListMyTeams200JSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams400ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams400ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams403ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams403ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyTeams500ApplicationProblemPlusJSONResponse Problem

func (response ListMyTeams500ApplicationProblemPlusJSONResponse) VisitListMyTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Revoke an invite link
	// (DELETE /invite-links/{code})
	RevokeInviteLink(ctx context.Context, request RevokeInviteLinkRequestObject) (RevokeInviteLinkResponseObject, error)
	// Join a team via an invite link
	// (POST /invite-links/{code}/acceptances)
	AcceptInviteLink(ctx context.Context, request AcceptInviteLinkRequestObject) (AcceptInviteLinkResponseObject, error)
	// Create a team
	// (POST /teams)
	CreateTeam(ctx context.Context, request CreateTeamRequestObject) (CreateTeamResponseObject, error)
	// Get a team
	// (GET /teams/{id})
	GetTeam(ctx context.Context, request GetTeamRequestObject) (GetTeamResponseObject, error)
	// List the team's invite links
	// (GET /teams/{team_id}/invite-links)
	ListInviteLinks(ctx context.Context, request ListInviteLinksRequestObject) (ListInviteLinksResponseObject, error)
	// Create an invite link
	// (POST /teams/{team_id}/invite-links)
	CreateInviteLink(ctx context.Context, request CreateInviteLinkRequestObject) (CreateInviteLinkResponseObject, error)
	// Get the caller
	// (GET /users/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Introduce yourself
	// (POST /users/me/introduction)
	CreateIntroduction(ctx context.Context, request CreateIntroductionRequestObject) (CreateIntroductionResponseObject, error)
	// List the caller's teams
	// (GET /users/me/teams)
	ListMyTeams(ctx context.Context, request ListMyTeamsRequestObject) (ListMyTeamsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RevokeInviteLink operation middleware
func (sh *strictHandler) RevokeInviteLink(w http.ResponseWriter, r *http.Request, code string, params RevokeInviteLinkParams) {
	var request RevokeInviteLinkRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeInviteLink(ctx, request.(RevokeInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeInviteLinkResponseObject); ok {
		if err := validResponse.VisitRevokeInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptInviteLink operation middleware
func (sh *strictHandler) AcceptInviteLink(w http.ResponseWriter, r *http.Request, code string, params AcceptInviteLinkParams) {
	var request AcceptInviteLinkRequestObject

	request.Code = code
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptInviteLink(ctx, request.(AcceptInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptInviteLinkResponseObject); ok {
		if err := validResponse.VisitAcceptInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTeam operation middleware
func (sh *strictHandler) CreateTeam(w http.ResponseWriter, r *http.Request, params CreateTeamParams) {
	var request CreateTeamRequestObject

	request.Params = params

	var body CreateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTeam(ctx, request.(CreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTeamResponseObject); ok {
		if err := validResponse.VisitCreateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTeam operation middleware
func (sh *strictHandler) GetTeam(w http.ResponseWriter, r *http.Request, id string, params GetTeamParams) {
	var request GetTeamRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeam(ctx, request.(GetTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTeamResponseObject); ok {
		if err := validResponse.VisitGetTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInviteLinks operation middleware
func (sh *strictHandler) ListInviteLinks(w http.ResponseWriter, r *http.Request, teamId string, params ListInviteLinksParams) {
	var request ListInviteLinksRequestObject

	request.TeamId = teamId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInviteLinks(ctx, request.(ListInviteLinksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInviteLinks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInviteLinksResponseObject); ok {
		if err := validResponse.VisitListInviteLinksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInviteLink operation middleware
func (sh *strictHandler) CreateInviteLink(w http.ResponseWriter, r *http.Request, teamId string, params CreateInviteLinkParams) {
	var request CreateInviteLinkRequestObject

	request.TeamId = teamId
	request.Params = params

	var body CreateInviteLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInviteLink(ctx, request.(CreateInviteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInviteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInviteLinkResponseObject); ok {
		if err := validResponse.VisitCreateInviteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request, params GetMeParams) {
	var request GetMeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIntroduction operation middleware
func (sh *strictHandler) CreateIntroduction(w http.ResponseWriter, r *http.Request, params CreateIntroductionParams) {
	var request CreateIntroductionRequestObject

	request.Params = params

	var body CreateIntroductionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIntroduction(ctx, request.(CreateIntroductionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIntroduction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateIntroductionResponseObject); ok {
		if err := validResponse.VisitCreateIntroductionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyTeams operation middleware
func (sh *strictHandler) ListMyTeams(w http.ResponseWriter, r *http.Request, params ListMyTeamsParams) {
	var request ListMyTeamsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyTeams(ctx, request.(ListMyTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyTeamsResponseObject); ok {
		if err := validResponse.VisitListMyTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvrchs3sn6VrjmpcnLOmKIvqRPzn+JkE205jsuRK6lytA440+QgwgATAEOaq2VVHiJPmCfZ6gbmQnJI",
	"SatY1pb9y7KES6PR/fXX3ZiLJDNlZTRq75LJRVIJK0r0aPl/P71yaE9y+jFHl1lZeWl0MklOsayMFXYF",
	"lRIZFkblaKHWXiqwKBSI2heovcwEzQB8K513IzjJ6ZcziQ58gZAJpdCOftZJmkhat0CRo03SRIsSk0ny",
	"032S4P5JnqSJxd9qaTFPJt7WmCYuK7AUJNvM2FL4ZJLUtaSRflXRZOet1PNkvV43g/lQx5mXCzzRC+nx",
	"mdTnP3jhkc9uTYXWS+Rh+LaSFt0bWri3RS483veyRBKyVkpMFTYSbe2bJs4LX4fVdF0mk9eJ4M2Ts10h",
	"+wd83cxM+2J0k8z0V8w87fDUovB4or01eZ2Rrl/ibzU6v3ug2qENar1IPrE4SybJ/xx1t38UVXT0qhm3",
	"LVO7wCFBGq32xNg0ne9L6b3Uc+hOBhlPdiBASX0OvhAeNC7QNoOCiVz7gnZ1vEfuUxTlXsVdRWm0wPMh",
	"pe1V2Ncsfn5FO8yvccwhu4urXNvw8n2G15gc5mQve2TflUO20wZESW9uo634B421U/quzJnJefsd2YKR",
	"Xv8iLj3MtgkEPbzJTK19TxKpPc7R7hyZBe5P2RC1keGwGtr7yyX5aim18MbSL0pRVXSYyUWDXXtOMQyr",
	"rR3tm7bHDeiIC3O+f97L8OcB3cXrXD0PISRaxDpNjMbvZ8nk9eHbGD7HOj08a88xLpu27xRn6zR5Yc1U",
	"YbmLoC//9hSePP78/yGOgK/QC6kczIyFb09PX8Dxi5NByMx54KB1S+280BluxlMrD8PLtmmmiZdeDftP",
	"+MVlq28Zd1iu3XLIivfocMexo0HdEEgbs7w6kPb2HRKfIscACv0HYCPzK5Ch9GbhjJfkFTZQZt/Bnse9",
	"SvH2Geq5L5LJg/E4TUqp2/8PiPhKy+HwssVCC4QKrWsJJgidgza+YH6hHIKYmtoT1yxBOjjXZqlhhX4E",
	"T4W1REO1AToO/Pn7HzQThAYsK78CozEFbTSC8CCUSsGZwEx+7kUxWEpf0BaCl/k5gUxoWmeK4ITMh7xw",
	"16hqfTAuDlvWkM5JWbdqTFcKcN0VDprTFaPVpiEciFM9Xe6NuLvWlW7ewr6jDFrmzaPOvnUvYw4Dc86i",
	"rho/3/SZZ2aJNhMOQaGnPC+FXM5l9J1a52hdZiy6FB6BN/DoIZgZO1AaKbnzwhKBTwF1To5mLOSmnir+",
	"WXNi160zAvJSoapCTNGTE2phrVnSyKq2lXE4ic4TvEt2KWImNPmRLIOTk5HAlD0zDC3RolqBRYflVKED",
	"6VM+Bjml1CDAST1XCEEB5Ot+aSArhBUZnb2dCiiyAowv0EKmjKNlUZt6XhBSVNIL5UBYBIuz2mEOVvBY",
	"XwgNM8p+8w4fSL4IS4Vw/F9XoSL9BDjooeGjhxtg+ChNKkHXQlf1j9fi/j/H95+cfdr88K83zU+f/e8n",
	"w4mu1DOze+tPDVmnIPULsKb2knQo3Dl4K7JztMwdPIrShQtzK+exBIuZsbkDXJDdwafLwkAuc1jSOVnT",
	"BerP+KfcMJp60qlRC4TM6JmSmXfdddAGQQWRJrSCHb84SdJkgdYFgcej8egBu0+FWlQymSSPRuPROGEF",
	"FQxrR5JD/n3KGd3RBfHgdTi6wqFw8Z2w56HuECaGZFOQFXCEHsH3Wq14gFlqtNHwWWqQBOnK6LkjryjF",
	"Ks4C6cOJ+By00wmBRyAlvTwj3SitvL4I9Q46S1ftiEx+f6FjJy4Mw0O301FTwVmf0bquMtqFmPBw/HhX",
	"Qyc9vTREZ50mj8fjkBlpjyElEVWlYm3nqAos9P9+dbTGRU/cQ9DVsFs22h0phJI52JiQswSPblOC07Y2",
	"xYBl/K5RkI7uObaNlBCQPJ0G9qgBgaZDtUAXKQSTDJ7MPk5r55jJHHOYSet8ClOcGYvtBjRCGboGqCsy",
	"M1bF41u+jNYk6HwzU+toFE9u+0r6bktIpiyKfNW31M9v21IJqoUCh5arVdaakKC7uiyFXbVIQLyyJz4h",
	"oJi7UBHpQCw5o7lDuHYksgwrztBCndYM1daO87xfWCVsE1BiOd0Cs20M7JBtBMe8EcVy6SgYl5UhXU7A",
	"mRIpllEM6Gm/3YB+585pIsUSGh14OMfEZnRhVO5iqAxigquzDDEPBCQrhJ6HQEKTQzCKpylr56EQC9zj",
	"ZOxD7GMh0oBD5gQuSuiIPBDUDgF2OPadBuxDpn09k+acc8Cej7fvtGc0fGlNbhWuKQ/XE6GwdhTza+1h",
	"GbHQCumIGE0xE/RX6cMABxWaSgVT+tVIvUWoKCehi+OFiABgHsHv4fjBO1fC34NAzbnvSgB88J4CYGZq",
	"xUk1U/GGnOfvNyofjrYrjHlAaEj5AleQM+JYjAE9IJMBV5hlh4tdteCuBdsH4/cZbLUBChBoYWnsuRvB",
	"jwWyu0YfjRGYeJCTZUXJU6iHNvQpl45CSi1dgfkEUPLspSComVl0RdguNAtpDiKnVCHFkJSbRSRammZT",
	"6bqLY2p2j6k5vq2UkDqNtE06yi3uuXihd5AgEN40EWshxbWYAmds+/nA07avFsxb51CK843mK8dHVt/1",
	"Y+2kWZjcMcbYtA22lC6Te2m6Fa6jaU6ww622bGKjftY4dt89h6J117XbjdPXCrAMsF+afPWXhZXdhuJ6",
	"s+pFHGG9E9zffVyj38dOa56ksdXOuz8zYaNdA3r18lnjeXFmiInD3ffBev76Y/z8cOPnHYTb4J8RuXro",
	"GqC0B6tHFzLnetIcB6D1Jfra6hZapysG0qbgv4lW36AfhqqBlELe7KnLHU8wGIN6JYQPt650qQdSOJau",
	"XyPqFYdCSbJXHOLsTHpwYtX5Z3DHZeRq7bz4GOu9MFw2gJbacuXM7xTbmvTzjiLIN+ivBB/0zxuZrzfq",
	"OZcCSo/7hY5+l4AbHiuUWsFMKo829ENCr6lXvabR9yKr41K1kq6D5W10eiZdr+7hroRS8Wg3hSpe+bca",
	"7apbuu2bdyttPZ7r3pSkB9vxtweF0mOg4Vd75tO9hkiEtWJ1SSroPnSsJBMmXHCIIaOLBt53lS4nbXGu",
	"7Ugx4KV9oGn/FCqfxGSkZzTqNXkoz4zZiVlqroj6gMdKTsmDUK12s9uuD9ikOKb2TuYN5WgeCCgUVseW",
	"p28fyH5lYg9N5OGoQrtlqORW1jAVF34jBFgUagTHOrr7sjAOu6xMm01AmSN3euMbB8V6aRLlERw3+lkW",
	"5pIIxTuHXijTQm9M274QetVkDWJqFtiLVMLfXWb4LKLkkHntT8PTS3Pv7k1rbGiz1nwofbYbHsLvkHtR",
	"Er0/Gb5m6fovQvA7kWzvvjpex5z7HaXYfSg/XMVr8u2PCM5YEg15gONEVP/QYfyDBuAmNb9GAbR2BDPh",
	"odMgrf6xMFsZRny20hjZKpQ5CRaHUjBkeo3xinKYWVMGhfc7VlLP0BIdR+VwSX+ekDmY2ivJ/X+9at4i",
	"laZE7beKoIUJz45C20lUVfOQSouSLNZlFlGD81IptgtvKJAIx1c6F1LvqTt8hzcskL6jAgE/VBwwkx/q",
	"LEPnZrWCZu+PDbi9BcQ7mhx3/tZzXvbULa89kr0Pl/a3MZ6LMvYs4rO6Ji0OHX8vSxzBq1irlA4KUVWo",
	"HQhVGucBF2hXoSIiXetnDAtl+/ZQuvCojVsUjlKNrRJoKH2Gt4fDdVCC/Rhe/FJm2CtnCEVcCluLgim3",
	"PJycd7GDMVrPIac9/vz9DyhQZwiPx082oObxeHyIBPb0eTc7I0Pfqt1yh2Qf+HTPaT9izoGmxa2++/pa",
	"RtOXrvH+9i0RP28i723riOzKISrONllgE2opQI/gS+MLblBuPlIll+Rozz4ZvynoO9+OI4e3TFNeLlI8",
	"Jc+D/wboiBoBSp4cCGvlAgOJXRrL76elhl/Clzm/tDDkUSkXvlsQlbB3mLS1TgMrU1uHanYZ6LdN64N1",
	"UB4Fy8BtN+vmQkMoBTa95kJWKeuNH6j7AqUFaxQlGpwQcBiwmKH2atW8OOLgQZSbKbjCmQ/Po/m/c7IV",
	"5npseUrS0G/Fgu5Lmyhci+8zIVVtMaC6Br5XYUNlNsaRYB2NmfULMPtqst+tTllR742/XamqeRqfSF1W",
	"z3zK1xdfzLqP3Z8rdH/Iirlyv2Q0nmI0Gqk5n+CPOMJrR4I9ha5FyJibcmITrV3oSIFoxjR0aRvICl8F",
	"UDIp1AbcbRUK+x842FohzGsRvw6wK8iNiej3X1DiyzbNcaCPQ/N4oeB021/RZEJBjgtUpqJ8LkmT2qpk",
	"khTeV5OjI0UDCuP85IvxF+OjxQN2x7jJ9mov+DVkV5sLqLlOLwaaZ26zhDc07GSzbtk0lvvJ8/ps/e8A",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
