# SPDX-FileCopyrightText: 2025-2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://mise.jdx.dev/schema/mise.json
min_version = "2026.7.0"

[settings]
always_keep_download = false
legacy_version_file = false

[tools]
"go" = "1.26.4"
"aqua:caarlos0/svu" = "3.4.1"
"aqua:crate-ci/typos" = "1.48.0"
"aqua:golangci/golangci-lint" = "2.12.2"
"aqua:goreleaser/goreleaser" = "2.17.0"
"aqua:go-task/task" = "3.52.0"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:tamasfe/taplo" = "0.10.0"
"aqua:golang-migrate/migrate" = "4.19.1"
"aqua:sqlc-dev/sqlc" = "1.31.1"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.1.4"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.7.2"
"npm:markdownlint-cli2" = "0.23.0"
"npm:renovate" = "43.252.1"
"npm:squawk-cli" = "2.59.0"
"pipx:reuse" = "6.2.0"
"pipx:yamllint" = "1.38.0"
"pipx:sqlfluff" = "4.2.2"

# indirect
"node" = "24.18.0"
"pipx" = "1.15.0"
"python" = "3.14.6"
"aqua:koalaman/shellcheck" = "0.11.0"

[env]
_.file = ".env"
