# SPDX-FileCopyrightText: 2025-2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://raw.githubusercontent.com/crate-ci/typos/master/config.schema.json

[files]
extend-exclude = [
    "internal/db/*.go",
    "internal/api/api.gen.go",
]
