// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertInviteLink = `-- name: InsertInviteLink :one
INSERT INTO invite_links (team_id, code, created_by_member_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, code, created_by_member_id, use_count, expires_at, revoked_at, created_at
`

type InsertInviteLinkParams struct {
	TeamID            uuid.UUID
	Code              string
	CreatedByMemberID uuid.UUID
	ExpiresAt         *time.Time
}

func (q *Queries) InsertInviteLink(ctx context.Context, arg InsertInviteLinkParams) (InviteLink, error) {
	row := q.db.QueryRow(ctx, insertInviteLink,
		arg.TeamID,
		arg.Code,
		arg.CreatedByMemberID,
		arg.ExpiresAt,
	)
	var i InviteLink
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Code,
		&i.CreatedByMemberID,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
