// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const isTeamOwner = `-- name: IsTeamOwner :one
SELECT EXISTS(
    SELECT 1
    FROM members
    WHERE
        team_id = $1
        AND user_id = $2
        AND role = 'owner'
        AND left_at IS NULL
)
`

type IsTeamOwnerParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

// Answers only whether the actor may act as owner of this team, and
// deliberately cannot say why not: a team that does not exist has no
// members, so it is indistinguishable from one the actor does not own.
// Nobody outside a team can learn that it exists by asking this.
func (q *Queries) IsTeamOwner(ctx context.Context, arg IsTeamOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamOwner, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinTeam = `-- name: JoinTeam :one
INSERT INTO members (team_id, user_id, role)
VALUES ($1, $2, 'member')
ON CONFLICT (team_id, user_id) DO UPDATE
    SET
        left_at = NULL,
        role = 'member'
    WHERE members.left_at IS NOT NULL
RETURNING id
`

type JoinTeamParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

// Joining is one statement, so it cannot half-happen: a newcomer is
// inserted, someone who had left is reinstated, and an active member is
// left alone.
//
// No row comes back for an active member, because DO UPDATE skips them.
// That absence is the answer rather than a failure: they asked to be in
// the team and already are. A returned row means somebody actually
// joined, which is exactly what the use count counts.
//
// Reinstating resets the role. Leaving a team gives up ownership, and an
// invitation brings a person back as a member, never as an owner.
func (q *Queries) JoinTeam(ctx context.Context, arg JoinTeamParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, joinTeam, arg.TeamID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
