// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertMember = `-- name: InsertMember :one
INSERT INTO members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, points, left_at, created_at
`

type InsertMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, insertMember, arg.TeamID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Points,
		&i.LeftAt,
		&i.CreatedAt,
	)
	return i, err
}
