// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Duty struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	Name        string
	Description *string
	Points      int64
	CreatedAt   time.Time
}

type Event struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	MemberID  uuid.UUID
	Type      string
	Payload   []byte
	CreatedAt time.Time
}

type Job struct {
	ID                uuid.UUID
	DutyID            uuid.UUID
	Status            string
	AssigneeMemberID  *uuid.UUID
	CreatedByMemberID uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Member struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	Points    int64
	LeftAt    *time.Time
	CreatedAt time.Time
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
}
