// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
)

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) InsertTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, insertTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
